// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/helio/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes = "Bearer.Scopes"
)

// Defines values for WhichStuff.
const (
	Bla  WhichStuff = "bla"
	Bla2 WhichStuff = "bla2"
	Bla3 WhichStuff = "bla3"
	Nope WhichStuff = "nope"
)

// CreateStuff defines model for CreateStuff.
type CreateStuff struct {
	union json.RawMessage
}

// CreateStuffBla defines model for CreateStuffBla.
type CreateStuffBla struct {
	Settings *StuffBla   `json:"settings,omitempty"`
	Which    *WhichStuff `json:"which"`
}

// CreateStuffNope defines model for CreateStuffNope.
type CreateStuffNope struct {
	Settings *StuffNope  `json:"settings,omitempty"`
	Which    *WhichStuff `json:"which"`
}

// CreateStuffProperties defines model for CreateStuffProperties.
type CreateStuffProperties struct {
	Which *WhichStuff `json:"which"`
}

// Stuff defines model for Stuff.
type Stuff struct {
	Which *WhichStuff `json:"which"`
}

// StuffBla defines model for StuffBla.
type StuffBla struct {
	Something *string `json:"something,omitempty"`
}

// StuffNope defines model for StuffNope.
type StuffNope struct {
	Nothing *string `json:"nothing,omitempty"`
}

// WhichStuff defines model for WhichStuff.
type WhichStuff string

// CreateStuffJSONRequestBody defines body for CreateStuff for application/json ContentType.
type CreateStuffJSONRequestBody = CreateStuff

// AsCreateStuffBla returns the union data inside the CreateStuff as a CreateStuffBla
func (t CreateStuff) AsCreateStuffBla() (CreateStuffBla, error) {
	var body CreateStuffBla
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateStuffBla overwrites any union data inside the CreateStuff as the provided CreateStuffBla
func (t *CreateStuff) FromCreateStuffBla(v CreateStuffBla) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateStuffBla performs a merge with any union data inside the CreateStuff, using the provided CreateStuffBla
func (t *CreateStuff) MergeCreateStuffBla(v CreateStuffBla) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateStuffNope returns the union data inside the CreateStuff as a CreateStuffNope
func (t CreateStuff) AsCreateStuffNope() (CreateStuffNope, error) {
	var body CreateStuffNope
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateStuffNope overwrites any union data inside the CreateStuff as the provided CreateStuffNope
func (t *CreateStuff) FromCreateStuffNope(v CreateStuffNope) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateStuffNope performs a merge with any union data inside the CreateStuff, using the provided CreateStuffNope
func (t *CreateStuff) MergeCreateStuffNope(v CreateStuffNope) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateStuff) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"which"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateStuff) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "bla":
		return t.AsCreateStuffBla()
	case "bla2":
		return t.AsCreateStuffBla()
	case "bla3":
		return t.AsCreateStuffBla()
	case "nope":
		return t.AsCreateStuffNope()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateStuff) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateStuff) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /stuff)
	CreateStuff(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateStuff converts echo context to params.
func (w *ServerInterfaceWrapper) CreateStuff(ctx echo.Context) error {
	var err error

	ctx.Set(BearerScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateStuff(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/stuff", wrapper.CreateStuff)

}
