openapi: 3.0.1

info:
  title: OpenAPI-CodeGen Test
  description: 'This is a test OpenAPI Spec'
  version: 1.0.0

servers:
  - url: https://test.oapi-codegen.com/v2
  - url: http://test.oapi-codegen.com/v2

paths:
  /stuff:
    post:
      description: Create stuff
      operationId: createStuff
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateStuff"
      responses:
        "201":
          description: created stuff
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stuff"
components:
  schemas:
    CreateStuff:
      oneOf:
        - $ref: "#/components/schemas/CreateStuffBla"
        - $ref: "#/components/schemas/CreateStuffNope"
      discriminator:
        propertyName: which
        mapping:
          bla: "#/components/schemas/CreateStuffBla"
          bla2: "#/components/schemas/CreateStuffBla"
          bla3: "#/components/schemas/CreateStuffBla"
          nope: "#/components/schemas/CreateStuffNope"
    CreateStuffProperties:
      type: object
      required:
        - which
      properties:
        which:
          $ref: "#/components/schemas/WhichStuff"
    CreateStuffBla:
      allOf:
        - $ref: "#/components/schemas/CreateStuffProperties"
        - type: object
          properties:
            settings:
              $ref: "#/components/schemas/StuffBla"
    CreateStuffNope:
      allOf:
        - $ref: "#/components/schemas/CreateStuffProperties"
        - type: object
          properties:
            settings:
              $ref: "#/components/schemas/StuffNope"
    Stuff:
      type: object
      required:
        - which
      properties:
        which:
          $ref: "#/components/schemas/WhichStuff"
    WhichStuff:
      type: string
      nullable: true
      enum:
        [
          bla,
          bla2,
          bla3,
          nope,
        ]
      default: bla
    StuffBla:
      type: object
      properties:
        something:
          type: string
    StuffNope:
      type: object
      properties:
        nothing:
          type: string
